// Mocks generated by Mockito 5.4.2 from annotations
// in defiraiser_mobile/test/feature/home/domain/usecases/make_donation_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i10;

import 'package:dartz/dartz.dart' as _i2;
import 'package:defiraiser_mobile/core/network/api_error.dart' as _i5;
import 'package:defiraiser_mobile/features/authentication/domain/entities/base_entity/base_entity.dart'
    as _i8;
import 'package:defiraiser_mobile/features/home/domain/entities/campaign_categories_entity/campaign_category_entities.dart'
    as _i6;
import 'package:defiraiser_mobile/features/home/domain/entities/campaigns/campaigns_entity.dart'
    as _i7;
import 'package:defiraiser_mobile/features/home/domain/entities/donors_entity/donors_entity.dart'
    as _i9;
import 'package:defiraiser_mobile/features/home/domain/repositories/campaign_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CampaignRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampaignRepository extends _i1.Mock
    implements _i3.CampaignRepository {
  MockCampaignRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i6.CampaignCategories>>
      getCategories() => (super.noSuchMethod(
            Invocation.method(
              #getCategories,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.ApiError, _i6.CampaignCategories>>.value(
                _FakeEither_0<_i5.ApiError, _i6.CampaignCategories>(
              this,
              Invocation.method(
                #getCategories,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.ApiError, _i6.CampaignCategories>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>> getCampaigns() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCampaigns,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>.value(
                _FakeEither_0<_i5.ApiError, _i7.CampaignResponse>(
          this,
          Invocation.method(
            #getCampaigns,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>> getMyCampaigns() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyCampaigns,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>.value(
                _FakeEither_0<_i5.ApiError, _i7.CampaignResponse>(
          this,
          Invocation.method(
            #getMyCampaigns,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>> getDonations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDonations,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>.value(
                _FakeEither_0<_i5.ApiError, _i7.CampaignResponse>(
          this,
          Invocation.method(
            #getDonations,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>
      getCampaignsByCategory({required String? id}) => (super.noSuchMethod(
            Invocation.method(
              #getCampaignsByCategory,
              [],
              {#id: id},
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>.value(
                _FakeEither_0<_i5.ApiError, _i7.CampaignResponse>(
              this,
              Invocation.method(
                #getCampaignsByCategory,
                [],
                {#id: id},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.ApiError, _i7.CampaignResponse>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>> getCurrentEthPrice() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentEthPrice,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>>.value(
            _FakeEither_0<_i5.ApiError, _i8.BaseEntity>(
          this,
          Invocation.method(
            #getCurrentEthPrice,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>> makeDonation({
    required String? campaignId,
    required String? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeDonation,
          [],
          {
            #campaignId: campaignId,
            #amount: amount,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>>.value(
            _FakeEither_0<_i5.ApiError, _i8.BaseEntity>(
          this,
          Invocation.method(
            #makeDonation,
            [],
            {
              #campaignId: campaignId,
              #amount: amount,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i9.DonorsEntity>> getDonors(
          {required String? campaignId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDonors,
          [],
          {#campaignId: campaignId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ApiError, _i9.DonorsEntity>>.value(
                _FakeEither_0<_i5.ApiError, _i9.DonorsEntity>(
          this,
          Invocation.method(
            #getDonors,
            [],
            {#campaignId: campaignId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i9.DonorsEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>> createDonation({
    required String? title,
    required String? description,
    required String? amount,
    required String? category,
    required String? deadline,
    required _i10.File? images,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDonation,
          [],
          {
            #title: title,
            #description: description,
            #amount: amount,
            #category: category,
            #deadline: deadline,
            #images: images,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>>.value(
            _FakeEither_0<_i5.ApiError, _i8.BaseEntity>(
          this,
          Invocation.method(
            #createDonation,
            [],
            {
              #title: title,
              #description: description,
              #amount: amount,
              #category: category,
              #deadline: deadline,
              #images: images,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i8.BaseEntity>>);
}
