// Mocks generated by Mockito 5.4.2 from annotations
// in defiraiser_mobile/test/feature/authentication/presentation/signup/state/bloc/sign_up_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:defiraiser_mobile/core/network/api_error.dart' as _i6;
import 'package:defiraiser_mobile/features/authentication/domain/entities/base_entity/base_entity.dart'
    as _i9;
import 'package:defiraiser_mobile/features/authentication/domain/entities/check_user_entity/check_user_entity.dart'
    as _i12;
import 'package:defiraiser_mobile/features/authentication/domain/entities/register_entity/create_account_response.dart'
    as _i7;
import 'package:defiraiser_mobile/features/authentication/domain/repositories/authentication_repository.dart'
    as _i2;
import 'package:defiraiser_mobile/features/authentication/domain/usecases/check_user_exist_usecase.dart'
    as _i11;
import 'package:defiraiser_mobile/features/authentication/domain/usecases/create_account_usecase.dart'
    as _i4;
import 'package:defiraiser_mobile/features/authentication/domain/usecases/create_user_password_usecase.dart'
    as _i10;
import 'package:defiraiser_mobile/features/authentication/domain/usecases/resend_otp_usecase.dart'
    as _i13;
import 'package:defiraiser_mobile/features/authentication/domain/usecases/verify_otp_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationRepository_0 extends _i1.SmartFake
    implements _i2.AuthenticationRepository {
  _FakeAuthenticationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreateUserAccountUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserAccountUsecase extends _i1.Mock
    implements _i4.CreateUserAccountUsecase {
  MockCreateUserAccountUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepository get authenticationRepository =>
      (super.noSuchMethod(
        Invocation.getter(#authenticationRepository),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authenticationRepository),
        ),
      ) as _i2.AuthenticationRepository);
  @override
  _i5.Future<_i3.Either<_i6.ApiError, _i7.CreateAccountResponse>> call(
          _i4.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.ApiError, _i7.CreateAccountResponse>>.value(
            _FakeEither_1<_i6.ApiError, _i7.CreateAccountResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.ApiError, _i7.CreateAccountResponse>>);
}

/// A class which mocks [VerifyOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpUseCase extends _i1.Mock implements _i8.VerifyOtpUseCase {
  MockVerifyOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepository get authenticationRepository =>
      (super.noSuchMethod(
        Invocation.getter(#authenticationRepository),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authenticationRepository),
        ),
      ) as _i2.AuthenticationRepository);
  @override
  _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>> call(
          _i8.VerifyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>>.value(
            _FakeEither_1<_i6.ApiError, _i9.BaseEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>>);
}

/// A class which mocks [CreateUserPasswordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserPasswordUsecase extends _i1.Mock
    implements _i10.CreateUserPasswordUsecase {
  MockCreateUserPasswordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepository get authenticationRepository =>
      (super.noSuchMethod(
        Invocation.getter(#authenticationRepository),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authenticationRepository),
        ),
      ) as _i2.AuthenticationRepository);
  @override
  _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>> call(
          _i10.CreatePasswordParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>>.value(
            _FakeEither_1<_i6.ApiError, _i9.BaseEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>>);
}

/// A class which mocks [CheckUsernameExistUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckUsernameExistUsecase extends _i1.Mock
    implements _i11.CheckUsernameExistUsecase {
  MockCheckUsernameExistUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepository get authenticationRepository =>
      (super.noSuchMethod(
        Invocation.getter(#authenticationRepository),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authenticationRepository),
        ),
      ) as _i2.AuthenticationRepository);
  @override
  _i5.Future<_i3.Either<_i6.ApiError, _i12.CheckUserEntity>> call(
          _i11.CheckUsernameExistParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.ApiError, _i12.CheckUserEntity>>.value(
                _FakeEither_1<_i6.ApiError, _i12.CheckUserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.ApiError, _i12.CheckUserEntity>>);
}

/// A class which mocks [ResendOtpUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendOtpUsecase extends _i1.Mock implements _i13.ResendOtpUsecase {
  MockResendOtpUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepository get authenticationRepository =>
      (super.noSuchMethod(
        Invocation.getter(#authenticationRepository),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#authenticationRepository),
        ),
      ) as _i2.AuthenticationRepository);
  @override
  _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>> call(
          _i13.ResendOtpParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>>.value(
            _FakeEither_1<_i6.ApiError, _i9.BaseEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.ApiError, _i9.BaseEntity>>);
}
